### ISSUE TITLE
Dashboard improvements

### ISSUE THREAD

**Issue by JohnSSB** [dhis2/who-data-quality-app#15]
**Consistency - time tab**
Better if the graph on the right has default level on district and not region. It would also be an advantage if the "guides lines" that distinguish between percentage deviations in scatter plots were removed. They give too much attention to small units.

**Consistency - data tab**

Is it correct to use the term dropout? It's not referring to same people (or is this a common way to use the term in DHIS2?)

Use dynamic graphs for "Consistency data"; In particular, histograms show little information when the y-axis is kept at 100% maximum at all times. By adjusting the maximum level on the y-axis of eg 5% over the highest observed percentage, the graph will be more intuitive. In that case, it is also important to point out that the y-axis is not 100%, but at X%.

 **Outliers  tab**

Consider dropping this tab. The outlier part does not work optimally, and much of the information here is better presented in the «consitency-time» tab. A good replacement can be to enter a "tables" tab. Where there is a table with the most important variables. Where the line starts at national level and where you can drill down.

**Comment by olavpo** [comment]
Some initial comments:

**consistency time tab**: 

- some countries have 30-40-50 orguntis at admin1 level, and 3-4-500 at admin2. It is already slow at admin1, so I'm not sure if going to admin2 by default is realistic.
- this I think is a general discussing across dashboard, in-depth module and annual report


**consistency data tab**

- these "dropout" indicators are well established/known by the target audience I think
- dynamic scale sounds like a good idea
