### ISSUE TITLE
Permit the administrator to select which sub-sections appear in the annual report

### ISSUE THREAD

**Issue by Bob-Pond** [dhis2/who-data-quality-app#5]
As it is, the report is too lengthy and users will find it hard to focus on the most important findings.  As one example, I find the entire "Summary" section to be unhelpful.  I like to skip it and jump to the detailed findings section.

**Comment by olavpo** [comment]
Bob, should this be done per user when running the report, or for all users per database?

I also agree that we should discuss how useful the summary itself is.

**Comment by Bob-Pond** [comment]
Hi Olav,

 

I would be happy if it could be done only by the administrator/superuser who is configuring the Tool.

 

Bob

**Comment by Bob-Pond** [comment]
Hi Olav,  I would be happy if only the administrator/superuser could use the Tool configuration function (Administration) to select which sections appeared in the Annual Report.  Cheers from Capetown
