### ISSUE TITLE
Problems with aggregation of reporting completeness

### ISSUE THREAD

**Issue by Bob-Pond** [dhis2/who-data-quality-app#6]
With several country instances (e.g. Liberia) when reporting completeness is aggregated over multiple years (e.g. for the "Overall score" in section 1d of the Annual Report), the result is substantially greater than 100%.  My guess is that DHIS2 administrators need guidance on how to define the aggregation for reporting completeness.

**Comment by varl** [comment]
If this is still relevant it should be reported in JIRA as issues in GitHub are not monitored.
