### ISSUE TITLE
Jira Rewrite-Epic description

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/who-data-quality-app#79]
Relates to: [DHIS2-6487](https://jira.dhis2.org/browse/DHIS2-6487):

The existing functionality is quite exhaustive. A qualitative rewrite requires a proper plan to move forward, so team apps met and worked out a plan on how to approach the app in a reasonable way. There are two main ways how to approach the rewrite: Firstly by simply starting and creating an app asap and secondly by starting with specifications first and then tackle different parts of the app step by step. The latter approach seems more safe, will ensure an higher quality of the app and less time spent in total to finish the whole app. The following is a plan that team app sketched out:

1. Divide app into manageable, prioritized chunks

Our idea is to develop the app iteratively by working on/adding/completing individual parts of the app. This will require us to identify parts of the app that we can work on individually and prioritize them. By doing that, we can release usable parts of the app and receive a reasonable amount of feedback & bug reports instead of being overwhelmed. Additionally we don't have to write specs / tests / documentation for the whole app, which would cost a lot of time.

Prioritization can't be done by the developers and dividing the app into individual, functional/usable parts requires someone who knows this app in depth. Organizing this step should be done by a project manager who connects a developer & a stakeholder with good knowledge about the app who work out individual parts and then discuss them with the project manager. Prioritization needs to be done by the project manager.

2. Create proper specs

Currently there are some loose / structure-less documents that describe the functionality of the app. These need be transformed into a consistent format (ideally Gherkin feature files). This can be done by teaming up developers with someone who knows the app quite well. The google docs can be used to extract the relevant information to create the specs for the first part of the app with the highest priority. This will reduce the amount of time this has to be done and fits nicely with the iterative approach.

Creating specs does not require a project manager, instead a team apps developer has to schedule a (possibly several) meeting(s) with someone who has good knowledge of this app. The project manager has to connect these two first though. Once specs have been worked out, UX (@cooper-joe) and the developer refine them to remove any UX blunder the dev/stakeholder might have introduced or adopted from the existing app.

3. Create parts of the app

Once feature files / specs are in place, the developers can start working on the app. As only a subset of the full functionality will be built during the first iteration, this should not take too much time and can be done side by side with steps 2 (see above) when creating the specs for the next part of the app that should be worked on while not slowing down the already-started development.

This step can be done by a developer and prioritization depends on team app's issue prioritization in Jira.

**Comment by ismay** [comment]
Well said, I think you worded it nicely. One thing that I'd like to add is that I feel input from a designer is also an important part of this process. The app could be built without, but it's very likely it'd result in an app with parts that have to be refactored afterwards. The most time efficient approach would be to include @cooper-joe in the process as well.

**Comment by Mohammer5** [comment]
I guess that should happen in part two, right? The dev meets with the stakeholder, creates specs and then @cooper-joe could have a look at both the existing app & the specs. This way we wouldn't occupy too much of his time

**Comment by ismay** [comment]
> I guess that should happen in part two, right? The dev meets with the stakeholder, creates specs and then @cooper-joe could have a look at both the existing app & the specs. This way we wouldn't occupy too much of his time

Yeah that sounds good 👍

**Comment by erikarenhill** [comment]
Sounds like a solid and thorough plan

**Comment by Mohammer5** [comment]
Issue description has been updated: [DHIS2-6487](https://jira.dhis2.org/browse/DHIS2-6487)
